<?php

use Drupal\Core\Routing\RouteMatchInterface;

function inline_menu_theme($existing, $type, $theme, $path) {
  return [
    'inline_menu' => [
      'variables' => [
        'menu_links' => [],
      ],
    ],
    'template_name' => [
      'variables' => ['options' => []],
    ]
  ];
}

/**
 * Implements hook_page_attachments().
 */
function inline_menu_page_attachments(array &$attachments) {
  if (\Drupal::service('router.admin_context')->isAdminRoute()) {
    $attachments['#attached']['library'][] = 'inline_menu/inline_menu';
  }
}
